### ISSUE TITLE
Deploy Core OODT Services to AWS

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/coal-sds#1]
This issue consists of deployment for OODT's core services e.g. [File Manager](https://cwiki.apache.org/confluence/display/OODT/OODT+Filemgr+User+Guide), [Workflow Manager](https://cwiki.apache.org/confluence/display/OODT/CAS-PGE+Learn+by+Example) and Resource Manager. I'll detail more on the [project wiki](https://github.com/capstone-coal/coal-sds/wiki) as I go along.

**Comment by lewismc** [comment]
@thomkenn how is progress coming along here? Have you checked out the source? Let me know how you are getting on, thanks.

**Comment by lewismc** [comment]
@thomkenn PING

**Comment by thomkenn** [comment]
So i have the aws instance properly configured. i was successfully able to build oodt and resolved all issues i had previously. the only issue i have is with deploying the oodt i have installed on my computer to the aws. Ill talk to you about this in the meeting

**Comment by thomkenn** [comment]
![image](https://user-images.githubusercontent.com/11286095/35973899-f5eee270-0c8b-11e8-8494-6dd893e8139d.png)

**Comment by thomkenn** [comment]
![image](https://user-images.githubusercontent.com/11286095/35974006-55a214d0-0c8c-11e8-9141-bba0cef1c451.png)

**Comment by thomkenn** [comment]
ok all issues have been resolved, i have clarified the instructions so that this is more streamlined in the future, if you arent a fan of these changes we can discuss them in the meeting!

File manager has been successfully configured and is running. Conducting tests on feeding in data now.

**Comment by lewismc** [comment]
> i have clarified the instructions

... what instructions? What are/were the changes?
