### ISSUE TITLE
Failure in updating Apache Tika 1.19.1 manually

### ISSUE THREAD

**Issue by DenimMazuki** [capstone-coal/coal-sds#24]
Tried to manually update Apache Tika to 1.19 to enable https://github.com/capstone-coal/coal-sds/issues/8 . Went and replaced the jar files in 
```
./crawler/lib/tika-core-1.10.jar
./crawler/lib/tika-parsers-1.7.jar
```
to 
```
./crawler/lib/tika-core-1.19.1.jar
./crawler/lib/tika-parsers-1.19.1.jar
```

When trying to run metadata extractor, the following error is obtained:
<img width="1046" alt="screen shot 2018-10-14 at 7 52 30 pm" src="https://user-images.githubusercontent.com/22643537/46927697-9cd0e480-cfeb-11e8-97e6-d83950470df2.png">

**Comment by lewismc** [comment]
@DenimMazuki this means that the commons-compress library (in particular) does not provide the adequate method for running an extraction... which in turn indicates that the version of commons-compress which is being read the from ClassPath is incorrect and probable needs upgraded.
In this case, the above us true and commons-compress (along with several other dependencies) need upgraded.
The list of dependencies is as follows

https://search.maven.org/artifact/org.apache.cxf/cxf-rt-rs-client/3.2.6/bundle
https://search.maven.org/artifact/javax.ws.rs/javax.ws.rs-api/2.1.1/bundle
https://search.maven.org/artifact/org.apache.tika/tika-core/1.19.1/bundle
https://search.maven.org/artifact/org.apache.tika/tika-parsers/1.19.1/bundle
https://search.maven.org/artifact/org.apache.commons/commons-compress/1.18/jar

Please download the Jar's and make them available within ```crawler/lib``` then re-run the extraction.
Thanks

**Comment by lewismc** [comment]
Also, @DenimMazuki please can you label your issues with the appropriate labels and version which the bug affects. Thank you
