### ISSUE TITLE
Attempt to update tika-* dependencies to 2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/coal-sds#28]
We should be able to do this because the http://repository.apache.org/snapshots/ repository is mentioned in parent pom.xml
https://github.com/capstone-coal/coal-sds/blob/master/pom.xml#L48-L55

**Comment by kristencheung** [comment]
<img width="1280" alt="screenshot 2018-10-29 22 03 17" src="https://user-images.githubusercontent.com/24422805/47697884-44dcd500-dbca-11e8-9740-9abc9acb0011.png">
<img width="1279" alt="screenshot 2018-10-29 22 33 19" src="https://user-images.githubusercontent.com/24422805/47697982-a4d37b80-dbca-11e8-9b51-290fbd6c5ba8.png">

We attempted to upgrade the Tika version to 2.0.0-SNAPSHOT by changing the version in pom.xml of COAL-SDS, however we were met with the errors listed above. It compiled fine in Maven, but we are not sure what other dependencies we are supposed to update.

**Comment by lewismc** [comment]
Fixed in commit https://github.com/capstone-coal/coal-sds/commit/8876c3460090eb5f9379eb150f44101048958121
