### ISSUE TITLE
Basic File Management

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/coal-sds#4]
Hi @thomkenn seeing as no issue has been opened yet, I am opening one here. 
The issue at hand is that we need to move forward with [basic file management](https://github.com/capstone-coal/coal-sds/wiki/Running-COAL-SDS#file-management). Once you install COAL-SDS (which should take around 3 minutes), please begin working your way through the [basic file management](https://github.com/capstone-coal/coal-sds/wiki/Running-COAL-SDS#file-management) documentation. 
Eventually, you will come to the [OODT File Manager User Guide](https://cwiki.apache.org/confluence/display/OODT/OODT+Filemgr+User+Guide). As I encouraged you to do, you need to read this guide in it's entirety. You then need to provide feedback on how file management works using one or more of the products staged by @bdegley4789 as an example. 
Please let me know how you get on with the above in the comments area below.
Thanks

**Comment by lewismc** [comment]
@thomkenn how are things coming along?

**Comment by thomkenn** [comment]
![image](https://user-images.githubusercontent.com/11286095/36199936-f23e20f2-112f-11e8-9d73-eec86ecbaec0.png)

i made some changes that necessetitates rebuilding, and i seem to be getting stuck on this screen. i think its possible a link or two that its pulling its downloads from may be out of date. im going over the file line by line to see where the issue might be. could also be a formatting issue on my end

**Comment by thomkenn** [comment]
Actually this is looking like a configuration issue. I'm consulting the email archives, I will have this working asap

**Comment by lewismc** [comment]
@thomkenn Do you have a branch of the codebase you can show your diff's at? 
Unless you provide something like that it is impossible for me to see what you are doing. lease provide, thanks.

**Comment by lewismc** [comment]
This issue was addressed via https://github.com/capstone-coal/coal-sds/pull/5
