### ISSUE TITLE
Configure OODT's PushPull Framework

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/coal-sds#7]
[OODT's PushPull component framework](https://cwiki.apache.org/confluence/display/OODT/OODT+Push-Pull+User+Guide) provides a client architecture for accessing an array of remote resources. This component is used to pull from remote resources and push to local ones. It is typically used in conjunction with the CAS Crawler component. An example use case would be pulling data products from a remote FTP service e.g. the AVIRIS FTP servers and pushing them to a local staging area e.g. the ones we use within basic file management, from which the [OODT CAS Crawler](https://cwiki.apache.org/confluence/display/OODT/OODT+Crawler+Help) then then inject them into the File Manager.

We need to add configuration for implemening PushPull.

**Comment by thomkenn** [comment]
The documentation in this issue appears to be out of date. i dont believe pushpull is currently an aspect of OODT, it appears to be now done through third party plugins.

**Comment by lewismc** [comment]
@thomkenn please leave this for the time being. Instead focus on #6
